[package]
name = "website"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = { version = "0.24.1", features = ["derive"] }
maud = "0.24.0"
grass = { version = "0.12.3", features = ["include_sass", "macro"] }
bytes = "1.4.0"
